### ISSUE TITLE
Transpilers | Integration | PM2 Documentation

### ISSUE THREAD

**Issue by rmonnier9** [keymetrics/doc-pm2#184]
https://pm2.io/doc/en/runtime/integration/transpilers/ 

 PM2 - Guide, References, Tutorials and Best Practices about PM2 and Node.js.

**Comment by Unitech** [comment]
> @gildarts
> typescritp?

Added: https://pm2.io/doc/en/runtime/integration/transpilers/#typescript

**Comment by FeklistovGleb** [comment]
How abount new babel-cli with "npx babel-cli" or "npx babel-node"?

**Comment by igufei** [comment]
pm2 start server.ts 
 -------------------------------------------------------------------------------------------------------------------------
server   │ 0  │ 1.0.0   │ fork │ N/A │ errored │ 0       │ 0      │ 0%  │ 0 B    │ Administrator │ disabled
 -------------------------------------------------------------------------------------------------------------------------
error log: 
PM2 error: Error: spawn F:\Node\nvm\v8.9.3\node_modules\pm2\node_modules\.bin\ts-node ENOENT
PM2        |     at _errnoException (util.js:1024:11)
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
PM2        |     at onErrorNT (internal/child_process.js:372:16)
PM2        |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
PM2        |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
 -------------------------------------------------------------------------------------------------------------------------
why?

**Comment by quartexNOR** [comment]
Any units for Smart Mobile Studio?  It compiles object-pascal (delphi), a special dialect tailored for JSVMs, to pristine Javascript.
Freepascal also have JS codegen. Object Pascal is highly productive and developers use Smart Pascal to write large JS based systems (the RTL have some 4000 classes, with proper VMT inheritance generated in JS). Would love to see PM2 expand to include these options
